public with sharing class TwilioSendGridDynamicTemplateData {
    /**
     * Dynamic template data is available using Handlebars syntax in Dynamic Transactional Templates. 
     * This field should be used in combination with a Dynamic Transactional Template, which can be identified by a template_id starting with d-. 
     * This field is a collection of key/value pairs following the pattern "variable_name":"value to insert".
     */

    public TwilioSendGridDynamicTemplateData() {}
}